name: Deploy to AWS ECS

on:
  push:
    branches: [master]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag with run number
        run: echo "TAG=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build and push Docker image to ECR
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_REPO:$TAG \
            --push .

      - name: Replace image URI in task definition
        run: |
          IMAGE_URI="$ECR_REPO:$TAG"
          sed "s|IMAGE_URI|$IMAGE_URI|g" task-definition.json > task-def-updated.json

      - name: Deploy to Amazon ECS with updated task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-def-updated.json
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: false